services:
  - type: web
    name: ezyago-trading-bot
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: ezyago-disk
      mountPath: /opt/render/project/storage
      sizeGB: 1
